In [1]:
import numpy as np

How to create an empty and a full NumPy array?

In [2]:
np.empty([2, 2])
np.full((2, 2), np.inf)

array([[inf, inf],
       [inf, inf]])

Create a Numpy array filled with all zeros

In [3]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

Create a Numpy array filled with all ones

In [4]:
np.ones_like(5)

array(1)

Check whether a Numpy array contains a specified row

In [5]:
arr = np.array([[1, 2, 3, 4, 5],
                   [6, 7, 8, 9, 10],
                   [11, 12, 13, 14, 15],
                   [16, 17, 18, 19, 20]
                   ])
print(arr)
print([1, 2, 3, 4, 5] in arr.tolist())

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]
True


How to Remove rows in Numpy array that contains non-numeric values?

In [6]:
n_arr = np.array([[10.5, 22.5, 3.8],
                  [41, np.nan, np.nan]])
print(n_arr)
print()
print(n_arr[~np.isnan(n_arr).any(axis=1)])

[[10.5 22.5  3.8]
 [41.   nan  nan]]

[[10.5 22.5  3.8]]


Remove single-dimensional entries from the shape of an array

In [7]:
x = np.zeros((3, 1, 4))
print(np.squeeze(x).shape)

(3, 4)


Find the number of occurrences of a sequence in a NumPy array

In [8]:
arr = np.array([[2, 8, 9, 4], 
                   [9, 4, 9, 4],
                   [4, 5, 9, 7],
                   [2, 9, 4, 3]])
output = repr(arr).count("9, 4")
print(output)

4


Find the most frequent value in a NumPy array

In [9]:
x = np.array([1,2,3,4,5,1,2,1,1,1])
print(np.bincount(x).argmax())

1


Combining a one and a two-dimensional NumPy Array

In [10]:
num_1d = np.arange(5)
print(num_1d)
num_2d = np.arange(10).reshape(2,5)
print()
print(num_2d)
print()
for a, b in np.nditer([num_1d, num_2d]):
    print("%d:%d" % (a, b),)

[0 1 2 3 4]

[[0 1 2 3 4]
 [5 6 7 8 9]]

0:0
1:1
2:2
3:3
4:4
0:5
1:6
2:7
3:8
4:9


How to build an array of all combinations of two NumPy arrays?

In [11]:
array_1 = np.array([1, 2])
array_2 = np.array([4, 6])

print(array_1)
print()
print(array_2)

comb_array = np.array(np.meshgrid(array_1, array_2)).T.reshape(-1, 2)
print()
print(comb_array)

[1 2]

[4 6]

[[1 4]
 [1 6]
 [2 4]
 [2 6]]


How to add a border around a NumPy array?

In [12]:
array = np.ones((2, 2))
  
print()
print(array)
  
print()
array = np.pad(array, pad_width=1, mode='constant',
               constant_values=0)
  
print(array)


[[1. 1.]
 [1. 1.]]

[[0. 0. 0. 0.]
 [0. 1. 1. 0.]
 [0. 1. 1. 0.]
 [0. 0. 0. 0.]]


How to compare two NumPy arrays?

In [13]:
an_array = np.array([[1, 2], [3, 4]])
another_array = np.array([[1, 2], [3, 4]])
 
comparison = an_array == another_array
equal_arrays = comparison.all()
 
print(equal_arrays)

True


How to check whether specified values are present in NumPy array?

In [14]:
n_array = np.array([[2, 3, 0],
                    [4, 1, 6]])
print(n_array)
print()
print(2 in n_array)
print(0 in n_array)

[[2 3 0]
 [4 1 6]]

True
True


How to get all 2D diagonals of a 3D NumPy array?

In [15]:
arr = np.arange(3 * 5 * 6).reshape(3, 5, 6)
print(arr)
diag_arr = np.diagonal(arr, 
                       axis1 = 1,
                       axis2 = 2)
  
print("\n", diag_arr)

[[[ 0  1  2  3  4  5]
  [ 6  7  8  9 10 11]
  [12 13 14 15 16 17]
  [18 19 20 21 22 23]
  [24 25 26 27 28 29]]

 [[30 31 32 33 34 35]
  [36 37 38 39 40 41]
  [42 43 44 45 46 47]
  [48 49 50 51 52 53]
  [54 55 56 57 58 59]]

 [[60 61 62 63 64 65]
  [66 67 68 69 70 71]
  [72 73 74 75 76 77]
  [78 79 80 81 82 83]
  [84 85 86 87 88 89]]]

 [[ 0  7 14 21 28]
 [30 37 44 51 58]
 [60 67 74 81 88]]


Flatten a Matrix in Python using NumPy

In [16]:
arr = np.array([[6, 9, 12], [8, 5, 2], [18, 21, 24]])
flat_arr = arr.flatten(order='A')
print(flat_arr)

[ 6  9 12  8  5  2 18 21 24]


Flatten a 2d numpy array into 1d array

In [17]:
ini_array1 = np.array([[1, 2, 3], [2, 4, 5], [1, 2, 3]])

print(str(ini_array1))

result = ini_array1.reshape([1, 9])

print("\n", result)

[[1 2 3]
 [2 4 5]
 [1 2 3]]

 [[1 2 3 2 4 5 1 2 3]]


Move axes of an array to new positions

In [18]:
arr = np.zeros((1, 2, 3, 4))
  
arr = np.moveaxis(arr, -1, 0).shape
  
print (arr)

(4, 1, 2, 3)


Interchange two axes of an array

In [19]:
x = np.array([[1,2,3]])
print(x)
y =  np.swapaxes(x,0,1)
print(y)

[[1 2 3]]
[[1]
 [2]
 [3]]


NumPy – Fibonacci Series using Binet Formula

In [20]:
fNumber = 10
a = np.arange(1, fNumber)
length_a = len(a)
sqrt_five = np.sqrt(5)
alpha = (1 + sqrt_five) / 2
beta = (1 - sqrt_five) / 2
Fn = np.rint(((alpha ** a) - (beta ** a)) / (sqrt_five))
print(Fn)

[ 1.  1.  2.  3.  5.  8. 13. 21. 34.]


Counts the number of non-zero values in the array

In [21]:
np.count_nonzero(np.eye(4))

4

Count the number of elements along a given axis

In [22]:
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
print(np.size(arr, 0))
print(np.size(arr, 1))

2
4


Trim the leading and/or trailing zeros from a 1-D array

In [23]:
arr = np.array((0, 0, 0, 0, 1, 5, 7, 0, 6, 2, 9, 0, 10, 0, 0))
res = np.trim_zeros(arr, 'f')
print(res)

[ 1  5  7  0  6  2  9  0 10  0  0]


Change data type of given numpy array

In [24]:
arr = np.array([10, 20, 30, 40, 50])
print(arr.dtype)
arr = arr.astype('float64')
print(arr)
print(arr.dtype)

int64
[10. 20. 30. 40. 50.]
float64


Reverse a numpy array

In [25]:
A = np.arange(8).reshape((2,2,2))
np.flip(A, 0)

array([[[4, 5],
        [6, 7]],

       [[0, 1],
        [2, 3]]])

How to make a NumPy array read-only?

In [26]:
a = np.zeros(11)
a.setflags(write=False)
try:
  a[1] = 7
except ValueError:
  print('Impossivel alterar')

Impossivel alterar




---



# **Questions on NumPy Matrix**

Get the maximum value from given matrix

In [27]:
matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
maximum = np.amax(matrix)
print(maximum)

9


Get the minimum value from given matrix

In [28]:
matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
minimum = np.amin(matrix)
print(minimum)

1


Find the number of rows and columns of a given matrix using NumPy

In [29]:
matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
rows, columns = matrix.shape
print(rows, columns)

3 3


Select the elements from a given matrix

In [30]:
matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

element = matrix[1, 1]
print(element)

row = matrix[1, :]
print(row)

column = matrix[:, 1]
print(column)

5
[4 5 6]
[2 5 8]


Find the sum of values in a matrix

In [31]:
matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

matrix_sum = np.sum(matrix)

print("Matrix: \n", matrix)
print("Sum of all values in the matrix: ", matrix_sum)

Matrix: 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Sum of all values in the matrix:  45


Calculate the sum of the diagonal elements of a NumPy array

In [32]:
matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Find the sum of the diagonal elements
diagonal_sum = np.trace(matrix)

print("Matrix: \n", matrix)
print("Sum of diagonal elements: ", diagonal_sum)

Matrix: 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Sum of diagonal elements:  15


Adding and Subtracting Matrices in Python

In [33]:
matrix1 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
matrix2 = np.array([[9, 8, 7], [6, 5, 4], [3, 2, 1]])

# Add the two matrices
matrix_sum = matrix1 + matrix2

# Subtract the two matrices
matrix_difference = matrix1 - matrix2

print("Matrix 1: \n", matrix1)
print("Matrix 2: \n", matrix2)
print("Sum of Matrices: \n", matrix_sum)
print("Difference of Matrices: \n", matrix_difference)

Matrix 1: 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Matrix 2: 
 [[9 8 7]
 [6 5 4]
 [3 2 1]]
Sum of Matrices: 
 [[10 10 10]
 [10 10 10]
 [10 10 10]]
Difference of Matrices: 
 [[-8 -6 -4]
 [-2  0  2]
 [ 4  6  8]]


Ways to add row/columns in numpy array

In [34]:
matrix = np.array([[1, 2, 3], [4, 5, 6]])

new_row = np.array([[7, 8, 9]])
matrix = np.concatenate((matrix, new_row), axis=0)

new_column = np.array([[10], [11], [12]])
matrix = np.concatenate((matrix, new_column), axis=1)

print("Original Array: \n", matrix)

Original Array: 
 [[ 1  2  3 10]
 [ 4  5  6 11]
 [ 7  8  9 12]]


Matrix Multiplication in NumPy

In [35]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

# Perform matrix multiplication
C = np.dot(A, B)

print("Matrix Multiplication: \n", C)

Matrix Multiplication: 
 [[19 22]
 [43 50]]


Get the eigen values of a matrix

In [36]:
A = np.array([[3, 2], [1, 2]])

eigenvalues = np.linalg.eigvals(A)

print("Eigenvalues: \n", eigenvalues)

Eigenvalues: 
 [4. 1.]


How to Calculate the determinant of a matrix using NumPy?

In [37]:
A = np.array([[3, 2], [1, 2]])

determinant = np.linalg.det(A)

print("Determinant: \n", determinant)

Determinant: 
 4.000000000000001


How to inverse a matrix using NumPy

In [38]:
A = np.array([[3, 2], [1, 2]])

inverse = np.linalg.inv(A)

print("Inverse: \n", inverse)

Inverse: 
 [[ 0.5  -0.5 ]
 [-0.25  0.75]]


How to count the frequency of unique values in NumPy array?

In [39]:
arr = np.array([1, 2, 3, 2, 1, 4, 4, 5, 5, 6, 6, 6])

unique_values, counts = np.unique(arr, return_counts=True)

print("Unique values: \n", unique_values)
print("Frequency counts: \n", counts)

Unique values: 
 [1 2 3 4 5 6]
Frequency counts: 
 [2 2 1 2 2 3]


Multiply matrices of complex numbers using NumPy in Python

In [40]:
arr = np.array([1, 2, 3, 2, 1, 4, 4, 5, 5, 6, 6, 6])

unique_values, counts = np.unique(arr, return_counts=True)

print("Unique values: \n", unique_values)
print("Frequency counts: \n", counts)

Unique values: 
 [1 2 3 4 5 6]
Frequency counts: 
 [2 2 1 2 2 3]


Compute the outer product of two given vectors using NumPy in Python

In [41]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

outer_product = np.outer(a, b)

print("Outer product: \n", outer_product)

Outer product: 
 [[ 4  5  6]
 [ 8 10 12]
 [12 15 18]]


Calculate inner, outer, and cross products of matrices and vectors using NumPy

In [42]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

inner_product = np.inner(a, b)

print("Inner product: ", inner_product)

outer_product = np.outer(a, b)

print("Outer product: \n", outer_product)

cross_product = np.cross(a, b)

print("Cross product: \n", cross_product)

Inner product:  32
Outer product: 
 [[ 4  5  6]
 [ 8 10 12]
 [12 15 18]]
Cross product: 
 [-3  6 -3]


Compute the covariance matrix of two given NumPy arrays

In [43]:
a = np.array([1, 2, 3, 4])
b = np.array([5, 6, 7, 8])

covariance_matrix = np.cov(a, b)

print("Covariance matrix: \n", covariance_matrix)

Covariance matrix: 
 [[1.66666667 1.66666667]
 [1.66666667 1.66666667]]


Convert covariance matrix to correlation matrix using Python

In [44]:
covariance_matrix = np.array([[2.5, 4.0], [4.0, 6.5]])

std_dev = np.sqrt(np.diag(covariance_matrix))

correlation_matrix = covariance_matrix / np.outer(std_dev, std_dev)

print("Correlation matrix: \n", correlation_matrix)

Correlation matrix: 
 [[1.         0.99227788]
 [0.99227788 1.        ]]


Convert covariance matrix to correlation matrix using Python

In [45]:
covariance_matrix = np.array([[2.5, 4.0], [4.0, 6.5]])

std_dev = np.sqrt(np.diag(covariance_matrix))

correlation_matrix = covariance_matrix / np.outer(std_dev, std_dev)

print("Correlation matrix: \n", correlation_matrix)

Correlation matrix: 
 [[1.         0.99227788]
 [0.99227788 1.        ]]


Compute the Kronecker product of two mulitdimension NumPy arrays

In [46]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])

# Compute the Kronecker product
kronecker_product = np.kron(a, b)

print("Kronecker product: \n", kronecker_product)

Kronecker product: 
 [[ 5  6 10 12]
 [ 7  8 14 16]
 [15 18 20 24]
 [21 24 28 32]]


Convert the matrix into a list

In [47]:
matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Convert the matrix into a list
matrix_list = matrix.tolist()



---

# **Questions on NumPy Indexing**

Replace NumPy array elements that doesn’t satisfy the given condition

In [48]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

# Define a condition
condition = arr < 5

# Replace elements that don't satisfy the condition
arr[condition] = 0

print("Array with replaced elements: \n", arr)

Array with replaced elements: 
 [ 0  0  0  0  5  6  7  8  9 10]


Return the indices of elements where the given condition is satisfied

In [49]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

# Define a condition
condition = arr > 5

# Find the indices of elements that satisfy the condition
indices = np.where(condition)

print("Indices of elements that satisfy the condition: \n", indices)

Indices of elements that satisfy the condition: 
 (array([5, 6, 7, 8, 9]),)


Replace NaN values with average of columns

In [50]:
arr = np.array([[1, 2, 3, 4, np.nan], [5, 6, 7, 8, 9], [10, np.nan, 12, 13, 14]])

# Replace NaN values with average of columns
for i in range(arr.shape[1]):
    col = arr[:, i]
    avg = np.nanmean(col)
    idx = np.isnan(col)
    col[idx] = avg

print("Array with NaN values replaced with average of columns: \n", arr)

Array with NaN values replaced with average of columns: 
 [[ 1.   2.   3.   4.  11.5]
 [ 5.   6.   7.   8.   9. ]
 [10.   4.  12.  13.  14. ]]


Replace negative value with zero in numpy array

In [51]:
arr = np.array([-1, 2, -3, 4, -5])

# Replace negative values with zero
arr = np.where(arr < 0, 0, arr)

print("Array with negative values replaced with zero: \n", arr)

Array with negative values replaced with zero: 
 [0 2 0 4 0]


How to get values of an NumPy array at certain index positions?

In [52]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

# Get the values at positions [2, 4, 6]
values = arr[np.array([2, 4, 6])]

print("Values at positions [2, 4, 6]: \n", values)

Values at positions [2, 4, 6]: 
 [3 5 7]


Find indices of elements equal to zero in a NumPy array

In [53]:
arr = np.array([1, 0, 2, 0, 3, 4, 0, 5, 6, 0])

# Find the indices of elements equal to zero
indices = np.where(arr == 0)

print("Indices of elements equal to zero: \n", indices)

Indices of elements equal to zero: 
 (array([1, 3, 6, 9]),)


How to Remove columns in Numpy array that contains non-numeric values?

In [54]:
arr = np.array([[1, 2, 3, '8'], [4, 5, 6, 7], [8, 9, '20', 10]])

# Convert the array to a float type to allow checking for NaN values
arr = arr.astype(float)

# Check for NaN values in each column
isnan = np.isnan(arr).any(axis=0)

# Remove the columns that contain NaN values
arr = arr[:, ~isnan]

print("Array with non-numeric values removed: \n", arr)

Array with non-numeric values removed: 
 [[ 1.  2.  3.  8.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 20. 10.]]


How to access different rows of a multidimensional NumPy array?

In [55]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Access the first row
first_row = arr[0,:]
print("First row: ", first_row)

# Access the second row
second_row = arr[1,:]
print("Second row: ", second_row)

# Access the third row
third_row = arr[2,:]
print("Third row: ", third_row)

# Access the first two rows
first_two_rows = arr[:2,:]
print("First two rows: \n", first_two_rows)

First row:  [1 2 3]
Second row:  [4 5 6]
Third row:  [7 8 9]
First two rows: 
 [[1 2 3]
 [4 5 6]]


Get row numbers of NumPy array having element larger than X

In [56]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Define a threshold value X
X = 5

# Get the row numbers where elements are larger than X
rows = np.where(arr > X)[0]

print("Rows where elements are larger than", X, ":", rows)

Rows where elements are larger than 5 : [1 2 2 2]


Get filled the diagonals of NumPy array

In [57]:
arr = np.zeros((3, 3))

# Fill the main diagonal with a given value
value = 1
np.fill_diagonal(arr, value)

print("Array with filled main diagonal:")
print(arr)

Array with filled main diagonal:
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


Check elements present in the NumPy array

In [58]:
arr = np.array([1, 2, 3, 4, 5])

# Using the in operator
print(3 in arr) # True
print(6 in arr) # False

# Using the isin() method
check_elements = [3, 6]
print(np.isin(check_elements, arr)) # [ True False]

True
False
[ True False]


Combined array index by index

In [59]:
arr1 = np.array([1, 2, 3, 4, 5])
arr2 = np.array([5, 4, 3, 2, 1])

# Using the np.add() function
result = np.add(arr1, arr2)
print(result) # [6 6 6 6 6]

# Using the addition operator
result = arr1 + arr2
print(result) # [6 6 6 6 6]

[6 6 6 6 6]
[6 6 6 6 6]


# **Questions on NumPy Linear Algebra**


---



Find a matrix or vector norm using NumPy

In [60]:
vector = np.array([1, 2, 3])
norm = np.linalg.norm(vector)
print(norm) # 3.7416573867739413

3.7416573867739413


Calculate the QR decomposition of a given matrix using NumPy

In [61]:
A = np.array([[1,2],[3,4]])

# Compute the QR decomposition
q, r = np.linalg.qr(A)

# Display the results
print("Q: \n", q)
print("R: \n", r)

Q: 
 [[-0.31622777 -0.9486833 ]
 [-0.9486833   0.31622777]]
R: 
 [[-3.16227766 -4.42718872]
 [ 0.         -0.63245553]]


Compute the condition number of a given matrix using NumPy

In [62]:
A = np.array([[1,2],[3,4]])

# Compute the condition number
condition_number = np.linalg.cond(A)

# Display the result
print("Condition number: ", condition_number)

Condition number:  14.933034373659268


Compute the eigenvalues and right eigenvectors of a given square array using NumPy?

In [63]:
A = np.array([[1,2],[3,4]])

# Compute the eigenvalues and right eigenvectors
eigenvalues, eigenvectors = np.linalg.eig(A)

# Display the results
print("Eigenvalues: ", eigenvalues)
print("Eigenvectors: \n", eigenvectors)

Eigenvalues:  [-0.37228132  5.37228132]
Eigenvectors: 
 [[-0.82456484 -0.41597356]
 [ 0.56576746 -0.90937671]]


Calculate the Euclidean distance using NumPy

In [64]:
def euclidean_distance(a, b):
    return np.linalg.norm(a - b)

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

distance = euclidean_distance(a, b)
print(distance)

5.196152422706632


# **Questions on NumPy Random**


---



Create a Numpy array with random values

In [65]:
a = np.random.rand(5)
print(a)

[0.59382687 0.72980646 0.67305069 0.41450948 0.58808486]


How to choose elements from the list with different probability using NumPy?

In [66]:
elements = [1, 2, 3, 4, 5]
probabilities = [0.1, 0.2, 0.3, 0.25, 0.15]

chosen_element = np.random.choice(elements, p=probabilities)
print(chosen_element)

3


How to get weighted random choice in Python?

In [67]:
items = ['A', 'B', 'C', 'D']
weights = [0.1, 0.2, 0.3, 0.4]
random_choice = np.random.choice(items, p=weights)
print(random_choice)

B


Generate Random Numbers From The Uniform Distribution using NumPy

In [69]:
# Generate a 1D array with 5 random numbers between 0 and 1
rand_1d = np.random.uniform(0, 1, 5)
print(rand_1d)

[0.1761486  0.20688764 0.71428062 0.42792162 0.21462541]


Get Random Elements form geometric distribution

In [70]:
rand_numbers = np.random.geometric(p=0.3, size=5)
print(rand_numbers)

[1 2 3 1 7]


Get Random elements from Laplace distribution

In [71]:
# Specifying the mean and scale parameters
loc = 0
scale = 1

# Generating random numbers from Laplace distribution
random_numbers = np.random.laplace(loc, scale, size=100)

Return a Matrix of random values from a uniform distribution

In [72]:
rand_matrix = np.random.rand(2, 3)
print(rand_matrix)

[[0.292989   0.57206538 0.23151319]
 [0.80524611 0.64748937 0.06685691]]


Return a Matrix of random values from a Gaussian distribution

In [73]:
mean = 5
stddev = 2
random_matrix = mean + stddev * np.random.randn(2, 3)
print(random_matrix)

[[6.77965741 7.31633841 8.07584054]
 [6.72864467 5.73683969 3.88580355]]


# **Questions on NumPy Sorting and Searching**


---



How to get the indices of the sorted array using NumPy in Python?

In [74]:
arr = np.array([5, 1, 9, 4, 2])
sorted_indices = np.argsort(arr)

print(sorted_indices)

[1 4 3 0 2]


Finding the k smallest values of a NumPy array

In [75]:
arr = np.array([3, 1, 4, 1, 5, 9, 2, 6, 5, 3, 5])
k = 4
k_smallest = np.partition(arr, k)
print(k_smallest[:k])

[1 1 2 3]


How to get the n-largest values of an array using NumPy?

In [76]:
arr = np.array([3, 2, 1, 4, 5, 6, 7, 8, 9])

n = 3

largest_values = np.partition(arr, -n)[-n:]

print(largest_values)

[7 8 9]


Sort the values in a matrix

In [80]:
matrix = np.array([[3, 2, 1], [6, 5, 4], [9, 8, 7]])
sorted_matrix = np.sort(matrix, axis=1)
print(sorted_matrix)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


Filter out integers from float numpy array

In [81]:
arr = np.array([3.14, 2.72, 4.67, 6.0, 8.1, 10.0, 11.23, 12.9])
filtered_array = arr[~np.isclose(arr % 1, 0)]
print(filtered_array)

[ 3.14  2.72  4.67  8.1  11.23 12.9 ]


Find the indices into a sorted array

In [82]:
arr = np.array([1, 3, 4, 7, 10])
value_to_find = np.array([2, 4, 5, 8])

index_positions = np.searchsorted(arr, value_to_find)

print("Indices of sorted array: ", index_positions)

Indices of sorted array:  [1 2 3 4]


# **Questions on NumPy Mathematics**


---



How to get element-wise true division of an array using Numpy?

In [83]:
array1 = np.array([2, 4, 6, 8])
array2 = np.array([1, 2, 3, 4])
result = np.true_divide(array1, array2)
print(result)

[2. 2. 2. 2.]


How to calculate the element-wise absolute value of NumPy array?

In [84]:
arr = np.array([-1, 2, -3, 4])
abs_arr = np.abs(arr)
print(abs_arr)

[1 2 3 4]


Compute the negative of the NumPy array

In [85]:
arr = np.array([1, 2, 3, 4, 5])

neg_arr = -arr

print(neg_arr)

[-1 -2 -3 -4 -5]


Multiply 2d numpy array corresponding to 1d array

In [86]:
# 2D array
arr_2d = np.array([[1, 2, 3], [4, 5, 6]])

# 1D array
arr_1d = np.array([2, 3, 4])

# Multiply the arrays
result = np.dot(arr_2d, arr_1d)

print(result)

[20 47]


Computes the inner product of two arrays

In [87]:
array_1 = np.array([1, 2, 3])
array_2 = np.array([4, 5, 6])

inner_product = np.dot(array_1, array_2)
print(inner_product)

32


Compute the nth percentile of the NumPy array

In [88]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

n = 90 # 90th percentile
percentile = np.percentile(arr, n)

print("The {}th percentile of the array is: {}".format(n, percentile))

The 90th percentile of the array is: 9.1


Calculate the n-th order discrete difference along the given axis

In [89]:
# Creating a sample 2D array
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Calculating the 2nd order difference along axis 0
diff_arr = np.diff(arr, n=2, axis=0)

print(diff_arr)

[[0 0 0]]


Calculate the sum of all columns in a 2D NumPy array

In [90]:
# Define a 2D array
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Calculate the sum of all columns
col_sum = arr.sum(axis = 0)

print(col_sum)
# Output: [12 15 18]

[12 15 18]


Calculate average values of two given NumPy arrays

In [91]:
array1 = np.array([1, 2, 3, 4, 5])
array2 = np.array([6, 7, 8, 9, 10])

average = (array1 + array2) / 2

print(average)

[3.5 4.5 5.5 6.5 7.5]


How to compute numerical negative value for all elements in a given NumPy array?

In [92]:
arr = np.array([1, -2, 3, -4, 5, -6])
negative_arr = np.negative(arr)

print(negative_arr)

[-1  2 -3  4 -5  6]


How to get the floor, ceiling and truncated values of the elements of a numpy array?

In [93]:
a = np.array([1.7, 2.6, 3.1, -0.5])

floor_values = np.floor(a)
ceil_values = np.ceil(a)
trunc_values = np.trunc(a)

print("Original Array:", a)
print("Floor Values:", floor_values)
print("Ceiling Values:", ceil_values)
print("Truncated Values:", trunc_values)

Original Array: [ 1.7  2.6  3.1 -0.5]
Floor Values: [ 1.  2.  3. -1.]
Ceiling Values: [ 2.  3.  4. -0.]
Truncated Values: [ 1.  2.  3. -0.]


How to round elements of the NumPy array to the nearest integer?

In [94]:
# Create a NumPy array
arr = np.array([1.2, 2.5, 3.7, 4.5, 5.1])

# Round elements of the array to the nearest integer
rounded_arr = np.around(arr)

# Print the rounded array
print(rounded_arr)

[1. 2. 4. 4. 5.]


Find the round off the values of the given matrix

In [95]:
matrix = np.array([[1.2, 2.5, 3.6], [4.1, 5.8, 6.3]])
rounded_matrix = np.around(matrix)

print(rounded_matrix)

[[1. 2. 4.]
 [4. 6. 6.]]


Determine the positive square-root of an array

In [96]:
arr = np.array([4, 9, 16, 25, 36])
result = np.sqrt(arr)
print(result)

[2. 3. 4. 5. 6.]


Evaluate Einstein’s summation convention of two multidimensional NumPy arrays

In [ ]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])

result = np.einsum('ij, jk -> ik', a, b)
print(result)

# **Questions on NumPy Statistics**


---



Compute the median of the flattened NumPy array

In [97]:
array = np.array([[3, 7, 5], [8, 4, 3], [2, 4, 9]])

# Flatten the array
flattened_array = array.flatten()

# Compute the median
median = np.median(flattened_array)

print("The median of the flattened array is:", median)

The median of the flattened array is: 4.0


Find Mean of a List of Numpy Array

In [98]:
arrays = [np.array([1, 2, 3]), np.array([4, 5, 6]), np.array([7, 8, 9])]
means = [np.mean(array) for array in arrays]
print(means)

[2.0, 5.0, 8.0]


Calculate the mean of array ignoring the NaN value

In [99]:
a = np.array([1, 2, np.nan, 4, 5])
mean = np.nanmean(a)
print(mean)

3.0


Get the mean value from given matrix

In [100]:
matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
mean = np.mean(matrix)
print("Mean of the matrix:", mean)

Mean of the matrix: 5.0


Compute the variance of the NumPy array

In [101]:
arr = np.array([1, 2, 3, 4, 5])
var = np.var(arr)
print("Variance:", var)

Variance: 2.0


Compute the standard deviation of the NumPy array

In [102]:
arr = np.array([1, 2, 3, 4, 5])

# calculate the standard deviation
std = np.std(arr)

# print the result
print(std)

1.4142135623730951


Compute pearson product-moment correlation coefficients of two given NumPy arrays

In [103]:
arr1 = np.array([1, 2, 3, 4, 5])
arr2 = np.array([5, 4, 3, 2, 1])

corr = np.corrcoef(arr1, arr2)
print(corr)

[[ 1. -1.]
 [-1.  1.]]


Calculate the mean across dimension in a 2D NumPy array

In [104]:
a = np.array([[1, 2, 3], [4, 5, 6]])
mean_across_rows = np.mean(a, axis=0)
print(mean_across_rows)

[2.5 3.5 4.5]


Calculate the average, variance and standard deviation in Python using NumPy

In [105]:
arr = np.array([1, 2, 3, 4, 5])

# Calculate the average of the array
mean = np.mean(arr)
print("Mean:", mean)

# Calculate the variance of the array
variance = np.var(arr)
print("Variance:", variance)

# Calculate the standard deviation of the array
std_dev = np.std(arr)
print("Standard Deviation:", std_dev)

Mean: 3.0
Variance: 2.0
Standard Deviation: 1.4142135623730951


Describe a NumPy Array in Python

In [106]:
print(dir(np.array))

['__call__', '__class__', '__delattr__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__le__', '__lt__', '__module__', '__name__', '__ne__', '__new__', '__qualname__', '__reduce__', '__reduce_ex__', '__repr__', '__self__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__text_signature__']


# **Questions on Polynomial**


---

